# Generated by Django 5.0.4 on 2024-04-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Adresses"},
        ),
    ]
