# Generated by Django 5.0.4 on 2024-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_address_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ref_code",
            field=models.CharField(blank=True, default=123, max_length=20, null=True),
        ),
    ]
