# Generated by Django 5.0.4 on 2024-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("S", "shirt"),
                    ("SH", "shorts"),
                    ("OW", "outwear"),
                    ("SHO", "shoes"),
                ],
                default=True,
                max_length=64,
            ),
        ),
    ]
