# Generated by Django 5.0.4 on 2024-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("shirt", "shirt"),
                    ("shorts", "shorts"),
                    ("outwear", "outwear"),
                    ("shoes", "shoes"),
                ],
                default=True,
                max_length=64,
            ),
        ),
    ]
