# Generated by Django 5.0.4 on 2024-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_item_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                choices=[
                    ("M", "30"),
                    ("L", "40"),
                    ("XL", "42"),
                    ("XXL", "44"),
                    ("S", "28"),
                ],
                default=True,
                max_length=64,
            ),
        ),
    ]
