# Generated by Django 5.0.4 on 2024-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_item_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "men"), ("B", "boys")],
                default="men",
                max_length=5,
                null=True,
            ),
        ),
    ]
