# Generated by Django 5.0.4 on 2024-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("men", "men"), ("boys", "boys")], default=True, max_length=5
            ),
        ),
    ]
