# Generated by Django 5.0.4 on 2024-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_item_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="discount_price",
            field=models.FloatField(blank=True, default=8.0, null=True),
        ),
    ]
