# Generated by Django 5.0.4 on 2024-04-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_item_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("men", "men"), ("boys", "boys")], default="men", max_length=5
            ),
        ),
    ]
