# Generated by Django 5.0.4 on 2024-04-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_order_ordered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
