# Generated by Django 5.0.4 on 2024-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_orderitem_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_amount",
            field=models.FloatField(default=5.0),
        ),
    ]
