# Generated by Django 5.0.4 on 2024-04-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[
                    ("P", "primary"),
                    ("S", "secondary"),
                    ("D", "danger"),
                    ("PU", "Puma"),
                ],
                default=True,
                max_length=64,
            ),
        ),
    ]
