# Generated by Django 5.0.4 on 2024-05-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("shirt", "shirt"),
                    ("shorts", "shorts"),
                    ("outwear", "outwear"),
                    ("shoes", "shoes"),
                    ("bats", "bats"),
                    ("t-shirts", "t-shirts"),
                    ("bags", "bags"),
                    ("pants", "pants"),
                    ("accessories", "accessories"),
                ],
                default=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(default="This is Text  Description", max_length=255),
        ),
    ]
